### ISSUE TITLE
Landing error

### ISSUE THREAD

**Issue by pavankay** [Janus1992/KSP_Starship-kOS-Interface#10]
I see this error just before starship performs the flip menuever
![Screenshot 2024-06-08 113158](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/5935949/d6c7f3c5-b134-41eb-9141-3fc34372d2af)

**Comment by pavankay** [comment]
also when trying again I get another error 
![1](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/5935949/abae1939-fd1f-4676-a2ed-97830c972a0c)

**Comment by Janus1992** [comment]
Did you change focus of the vessel right before the flip when the first screenshot happened? Also, why is it so far off target? What happened beforehand?

Can you add the starship.ks under Kerbal Space Program/Ships/Script/ here? (I'm on a different version and can't track the errors until I have yours)

**Comment by pavankay** [comment]
Sure. To awnser your first question I did not change my foucus the whole time and let the code do it for me,

I will paste in a .txt version of the ks code
[starship.txt](https://github.com/user-attachments/files/15749440/starship.txt)

**Comment by Janus1992** [comment]
Okay the first error should not pop up anymore in the next upload (next few days). Nice find, I never experienced that one myself.
The second one I also found out recently while messing around with FAR (which is still highly problematic). Will also be fixed soon!

**Comment by pavankay** [comment]
What is far and also do you know why the first one happend?

**Comment by pavankay** [comment]
and did you figure out why it was so far from target?

**Comment by Janus1992** [comment]
Ferram Aerospace Research. Makes planes better, but Starship considerably worse.
The first one happened when it couldn't reach the target (for whatever reason) and at 10km altitude it triggers the searching for a new relatively flat landing zone and that is when kOS had a slight hiccup. My fix will guard against that hiccup (it shouldn't really happen, yet it does).
As to why it couldn't reach the target, you can best describe what it tried to do. I can't see that, and it doesn't really happen to me (after doing an automatic deorbit burn).

**Comment by pavankay** [comment]
Ferram Aerospace Research is not installed though.

**Comment by pavankay** [comment]
Thank you for explaining it to me as I dont know much about kOS,

**Comment by Janus1992** [comment]
no worries! Keep the bug reports coming, I can fix a lot of bugs (that I didn't find) this way!

**Comment by pavankay** [comment]
just wondering how did you get the frosting on starship in your video and mods did you have installed then?

**Comment by Janus1992** [comment]
The frost is a separate mod available on the discord. It will be included in SEP at some point in the future (and then also in my .crafts). I don't use it yet, but will once it's a SEP standard!

**Comment by pavankay** [comment]
what other visual mods did you have?

**Comment by Janus1992** [comment]
not my video, so don't know. I'm running bare minimum

**Comment by pavankay** [comment]
Oh sorry did not know, Thank you for help!
