### ISSUE TITLE
On launch

### ISSUE THREAD

**Issue by pavankay** [Janus1992/KSP_Starship-kOS-Interface#11]
Not sure who I should talk to about this but after the restack on Superheavy and Starship after I refuel and everything starship just falls of the booster. Is this something you can fix?

**Comment by Janus1992** [comment]
I assume you are using Kerbal Joint Reinforcement Continued?
If so, can you describe it more accurately? Like the moment it happens, screenshots, etc?

**Comment by pavankay** [comment]
Sorry for not responding, I wont be able to boot up ksp until later today.

**Comment by Janus1992** [comment]
Is this still an issue? Did KJR fix it?

**Comment by Janus1992** [comment]
I found the issue! When I rebuilt the .craft files with the new HSR I forgot to auto-strut the ships body. It's fixed now!
