### ISSUE TITLE
Booster smashes into tower in KSRSS 2.5x

### ISSUE THREAD

**Issue by MiaFoxcat** [Janus1992/KSP_Starship-kOS-Interface#12]
Pretty self-explanatory... Playing KSRSS 2.5x, and superheavy quite reliably smashes into the OLM tower during the landing burn - it lands roughly 10-20 meters long.

**Comment by Janus1992** [comment]
The landing burn is still under adaptation after IFT4, and will be started even later when the next update is out.
Nevertheless, it shouldn't do that. What's the final LngError value at the moment of landing burn start? Could you provide a screenshot with the kOS terminal opened at that particular moment?

**Comment by MiaFoxcat** [comment]
Got one as the burn was starting and one at the end
![screenshot7](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/f14b76f1-50ee-4612-ad2d-20a5597eefcc)
![screenshot8](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/211780aa-2782-4a9e-b04a-3a024b80306c)

**Comment by MiaFoxcat** [comment]
Seems that the launchpad coords are wrong - I replaced the ending 96 in longitude with 4 and it works now? Just the chopsticks don't want to cooperate

**Comment by wastedemu** [comment]
On my install, the engine section of the booster always hits the top of the tower. Only happened after the latest update with the IFT-4 profile a few days ago

**Comment by MiaFoxcat** [comment]
I'm currently doing some tweaking to make it work. I've managed to tweak the longitude and now working out the mechazilla timing. May send the files if it happens to work.

**Comment by Janus1992** [comment]
Interesting! If you enable the showing of Trajectories in-flight, do you see if the LZ is offset from the OLM? Also, could you post the coordinates?

**Comment by MiaFoxcat** [comment]
The coordinates are 28.50895 (lat) and -81.203375 (lon)
I'm not sure, however currently I'm trying to solve the mechazilla not responding correctly - being generally too slow and not catching the booster.

**Comment by Janus1992** [comment]
Thanks. I'll look at it in a few days when I have the time. I also noticed problems with the arms being too slow on occasion. Not sure exactly why this happens, but I'm making some changes in the next updates.

**Comment by Janus1992** [comment]
If you find time, could you check if the bug is still there with the latest version? I made some changes and I am looking for some feedback

**Comment by MiaFoxcat** [comment]
Will check tomorrow (about ~18h from now at most) and let you know.

**Comment by MiaFoxcat** [comment]
The landing zone moved the right amount, but exactly the opposite way

**Comment by Janus1992** [comment]
I didn't move the landing zone, just changed the guidance. Got any screenshots again?

**Comment by MiaFoxcat** [comment]
![screenshot20](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/a2b5256e-e955-4951-b3f1-9bb4aba85418)

**Comment by Janus1992** [comment]
Another screenshot at 1500m, and also one at 500m please. This looks weird! Does it slam into the ground?

**Comment by MiaFoxcat** [comment]
I'll grab them once home. It lands softly, but tells me it's too far from mechazilla.

**Comment by Janus1992** [comment]
Maybe it happens due to the fact it's 2.5x sized. I thought KSRSS is 2.7x? Can you provide a source to your download?

Rescaled 2.5x I haven't gotten around to changing yet. EDIT: Caught on the first try..


What might be useful info:

Go to the booster terminal (anytime), press Ctrl + C and type in this:
print ship:body.   (always with the dot at the end)
print ship:body:name.
print ship:body:radius.
print rescale.

Screenshot the results

**Comment by MiaFoxcat** [comment]
I just round to 2.5x, but it is indeed 2.7x. I just arrived home and I'll see how tired I'll be, so I might either send it today or tomorrow morning.

**Comment by MiaFoxcat** [comment]
![screenshot21](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/6b06ab21-1eda-4a57-84ca-8959f20ec03b)
![screenshot22](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/21e54279-a662-4de3-8a57-2ee89a30f607)

**Comment by Janus1992** [comment]
I'm surprised it still overshoots the tower. Which ship did you launch before? Cargo/Tanker/Depot/Crew?
If you get around to it, can you also send a ksp.log in here?

**Comment by MiaFoxcat** [comment]
Tanker, haven't tried with the others... I updated by deleting the folder in GameData and then placing the KSP/ folder in KSP root, is that correct?

**Comment by Janus1992** [comment]
Probably yes, I describe what it should look like in the readme

**Comment by Janus1992** [comment]
Here are some screenshots of mine. Ours are remarkably similar, with one notable exception.
![Screenshot_20240620_203447](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/108296902/169cca6c-3996-437b-81ab-bc2209a20a16)
![Screenshot_20240620_203457](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/108296902/b91939ca-48c2-4e20-8666-cb483cd76a51)
On mine the landing ratio (and therefore throttle) is 0.98 and on yours it's 1.3 which means it has either started the landing burn later or the vehicle is not slowing down as fast as it should. Are you running any kind of MechJeb throttle smoother or thrust/Q limiter?

![Screenshot_20240620_203533](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/108296902/30a0c8ac-dd05-4d90-af2c-c536357451bd)

**Comment by MiaFoxcat** [comment]
I shouldn't be, MJ is white on all options

**Comment by Janus1992** [comment]
Then the only thing I can imagine that is different is the booster mass. Perhaps I made a mistake with Community Resource Pack and its LqdMethane fuel amount? I uploaded a new booster script which should also print the booster mass. Could you use that to make screenshots of right before the landing burn and various points during the landing burn? We could confirm if mass is the issue like this.

EDIT: Maybe also keep the booster cluster menu open so I can see its actual thrust. Also I checked the LqdMethane amount and it fits for the mass it should have..

**Comment by MiaFoxcat** [comment]
![screenshot24](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/6252bb1b-a4b9-427c-afd9-529bc21dbedf)
![screenshot25](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/60871255/7ee6d3d1-4eae-410f-b3f2-319d1c219fbc)

**Comment by Janus1992** [comment]
I don't see any error in the thrust levels. Mass/Thrust are also fine, so it must be something else.
You do seem to have options for persistent thrust and things. Can you either:
- Send me a ksp.log, and/or ..
- Temporarily take out (read: move to another folder) any non-required mods and see if it fixes your problem.

Let me know if you find out what mod is causing this behaviour, as I may try it out myself and see if I can make a fix for it.

**Comment by MiaFoxcat** [comment]
Hmm, seems that removing PersistentThrust fixed it. Thanks for the tip!
