### ISSUE TITLE
On booster auto landing it says "Mechazilla out of range" every single time. It works perfectly for the Starship from orbit.

### ISSUE THREAD

**Issue by Toucanto** [Janus1992/KSP_Starship-kOS-Interface#13]
**Describe the bug**
On automatic landing for the booster on any Starship, it does the boostback burn perfectly, but fails to be caught every single time. It lands extremely close to the arms, but misses every time and slams into the ground at >50 m/s. 

**KSP.log file**
[https://1drv.ms/u/s!Aklkm9a5OdxAjJYjbbomg032gTm5gA?e=o1VTeg](url)
KSP.log uploaded to OneDrive because it is above the 25MB limit
**To Reproduce**
1. Put the stock cargo Starship onto the pad
2. launch like normal
3. once booster seperation and boostback happens, it goes to ksc but fails with the error 
4. "Mechazilla out of range"

**Expected behavior**
For the booster to be caught and be able to be recovered.

**Screenshots**
will add screenshot when i can get amd adrenaline to finally work and take one lmao

**Additional context**

**Comment by Toucanto** [comment]
update, i tried to reopen ksp and now the mod isint working pretty much at all, the buttons and the full interface shows up; but nothing works. the buttons as i click them have the white bar beneath them but i can do it for multiple of the window tabs. i didint change any files, all i did was reboot the game. I disabled windows defender in case it was deleting files, no dice.

**Comment by Janus1992** [comment]
Your log says you have FAR installed. I never got that working reliably (or at all since a while). I put it back into the list of not supported mods a while back. Sorry!
