### ISSUE TITLE
missing part sle.ss.olm.kos

### ISSUE THREAD

**Issue by TheAbider** [Janus1992/KSP_Starship-kOS-Interface#3]
When trying to load your craft files I am getting a missing part error for "sle.ss.olm.kos". I am using the dev build of SLE as requested and do see a file for SLE_SS_OLM but not kos. Any ideas?

**Comment by Janus1992** [comment]
Can you try again with the latest version of yesterday? I am aware there were some patching errors happening that I've tried to fix, and these fixes seemed to work for one other person that reported the same problem. There may still be another cause though.

**Comment by ayrtonkee** [comment]
I can confirm that this is also happening with the latest version of both your interface and SEP

**Comment by ayrtonkee** [comment]
This was also happening to me. I found out that CKAN doesn't update SLE to the latest dev version.
After I downloaded the latest version from their github, it worked again!
