### ISSUE TITLE
Qd To Qd breaks the booster script

### ISSUE THREAD

**Issue by TheKSPMan** [Janus1992/KSP_Starship-kOS-Interface#4]
Qd to qd breaks the booster landing sequence, with butt to butt it works perfectly.

**Comment by Janus1992** [comment]
Could you be a little more specific about what it breaks in the sequence? Are you changing the default setting from the .craft files I'm providing? It's set on purpose to butt-to-butt by default and gets changed to qd-to-qd sometime during launch automatically. There's no other way to ensure the right docking system at the moment, so it's probably not a bug.

**Comment by TheKSPMan** [comment]
I am using your .craft files. It breaks right after the booster seperation. Tomorrow I'll check out if it switches to QD to QD.

**Comment by Janus1992** [comment]
Okay, so I added a check right at booster separation that makes sure the right setting is selected. Should work now regardless of what you set in the VAB. However please try to use the .craft as is in the future to ensure that the script continues working properly.
