### ISSUE TITLE
I get this message when I load a craft

### ISSUE THREAD

**Issue by mariocmg** [Janus1992/KSP_Starship-kOS-Interface#5]
![image](https://user-images.githubusercontent.com/38396612/224548582-390d9540-eea0-4635-8b69-0995530f077d.png)

**Comment by Janus1992** [comment]
Could you download the Interface again and overwrite? I changed something that may fix your problems.

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/224725527-a8453206-eb77-4836-a26f-4c22e45a3947.png)
I continue having issues

**Comment by Janus1992** [comment]
Looks like you don't fulfill the requirements of the interface and the patch doesn't get applied. Could you read through the github to see if you are missing anything important and send your ksp.log in here so I could take a look at that. Maybe some screenshots of your gamedata folder would be nice, and perhaps also of the starship parts in the VAB. Do the default SEP parts show up?

**Comment by mariocmg** [comment]
Okey, I have try to reinstall everything and now its load correctly

**Comment by mariocmg** [comment]
But I load the ship on the platform, and the interface appears, but after a few seconds it disappears.

**Comment by Janus1992** [comment]
Great to hear that at least everything shows up. Could you keep the ships cpu open and screenshot any errors that turn up on loading?

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/225078599-621ec0a6-7ff4-47eb-bfe2-8919afb109dc.png)

**Comment by mariocmg** [comment]
Okay, I found the error, I didn't have the game in English. Thank you very much for the help.

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/225089872-e1ef3e15-07a3-41e0-9f09-1905c6d8bb1a.png)
Well, now I have this issue while making the deorbit burn and landing

**Comment by Janus1992** [comment]
It's again an autoloc problem. As if the language is still set to something else. Or a mod is interfering. Could you try running ksp with only the required mods? Something is causing these errors.

**Comment by mariocmg** [comment]
I have try and I have the same issue

**Comment by Janus1992** [comment]
Okay, the problem seems to be happening only for people that do not have Breaking Ground installed. I'm going to try to make a fix so that you don't need Breaking Ground. I'll report back.

**Comment by Janus1992** [comment]
So, with the new update this crash shouldn't happen anymore. Thanks for reporting the bug! 
Let me know if it works properly.

**Comment by mariocmg** [comment]
![image](https://user-images.githubusercontent.com/38396612/226651397-7b3f47cd-62e4-464d-a754-38a8c6e02435.png)
Now everything goes well except at the end of the re-entry the interface restarts all the time.

**Comment by Janus1992** [comment]
oh yeah. I was running out of time before going on holiday, so I couldn't do a whole flight to check. I will fix it first thing on sunday when I get back. Sorry.

**Comment by Janus1992** [comment]
Alright, I got around to fixing it. I hope it all works properly now!

**Comment by mariocmg** [comment]
Now works perfect. Thanks for your work

**Comment by Janus1992** [comment]
No problem! Thanks for your patience! Some use cases tend to slip under since I don't get the errors. Thanks again for reporting the issues ;)
