### ISSUE TITLE
Parts clipping into each other when loading a craft file

### ISSUE THREAD

**Issue by The0n1y5pace4ce** [Janus1992/KSP_Starship-kOS-Interface#6]
This happens when selecting one of the craft files, latest SEP, SLE and KOS interface versions, happy to send a screenshot of gamedata folder if needed.
![image](https://user-images.githubusercontent.com/90187370/224663611-fffabe62-6836-416f-a772-5780e40fe8b9.png)

**Comment by Janus1992** [comment]
Can you send a screenshot from the VAB where you load the vehicle? The craft is not even centered in the middle of the tower, so there's more going on. Maybe also try a reinstall in the meanwhile (delete all related folders like SEP and SLE from gamedata first)? If that doesn't help, send me your ksp.log

**Comment by The0n1y5pace4ce** [comment]
Sure thing, here: 
![image](https://user-images.githubusercontent.com/90187370/224827948-f95e2f15-e5e9-4b13-8af6-cbd42573af4a.png)
****

**Comment by Janus1992** [comment]
Looks like you are not running stock KSP, which is the only one I'll support until I've got all the patching problems under control. Which mods are you running?

**Comment by The0n1y5pace4ce** [comment]
I am so sorry, i have just realized that somehow RSS snuck its way into my mods, i will run it now to make sure it works

**Comment by The0n1y5pace4ce** [comment]
hmm, still the same issue, gamedata is here: 

![image](https://user-images.githubusercontent.com/90187370/225226069-e13dd603-ebc0-416f-a147-341a0ac08b21.png)
![image](https://user-images.githubusercontent.com/90187370/225226127-9a0c59a0-282e-4570-8b3b-08af9fc693fa.png)
![image](https://user-images.githubusercontent.com/90187370/225226171-8edc536e-bf1e-4acb-8618-bd23e37f0982.png)

**Comment by The0n1y5pace4ce** [comment]
works, now, just needed a new save
