### ISSUE TITLE
Landing Issues

### ISSUE THREAD

**Issue by stocky789** [Janus1992/KSP_Starship-kOS-Interface#7]
There is currently an issue with the autoland with the KoS script. The booster waits to long before doing a landing burn and just smashes into the ground 

Then the autoland on the ship starts its deorbit burn then once finished it just stops the auto land function.

**Comment by Janus1992** [comment]
Please check that all requirements are installed properly according the readme. Please keep the boosters cpu open and make screenshots of any crashes that happen. 

Same for the ships cpu's. After deorbit burn the script may crash occasionally but should be restarted by the watchdog cpu after a few seconds and then reengage the autoland function without any further problems. Please show screenshots if that doesn't happen

**Comment by Janus1992** [comment]
Okay, FAR has been added to the list of incompatible mods.
