### ISSUE TITLE
Loading ship error

### ISSUE THREAD

**Issue by pavankay** [Janus1992/KSP_Starship-kOS-Interface#9]
When I load the ship I see 
![Screenshot 2024-06-07 212717](https://github.com/Janus1992/KSP_Starship-kOS-Interface/assets/5935949/4b911590-0729-4a4b-ae15-fc9439f835d0)

**Comment by Janus1992** [comment]
Be sure to download the dev branches of both SEP and SLE. They include the new parts, and I assume that that'll work!

**Comment by pavankay** [comment]
thank you! that worked
